#!/usr/bin/env python3
"""Build deterministic per-architecture DataFlow air-gap release bundles."""

from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import os
import shutil
import tarfile
import tempfile
from pathlib import Path

KUBERAY_VERSION = "1.6.2"
KUBERAY_OPERATOR_IMAGE = f"quay.io/kuberay/operator:v{KUBERAY_VERSION}"
POSTGRES_IMAGE = "postgres:16-alpine"
MINIO_IMAGE = "dataflow-minio-reference:RELEASE.2025-09-07T16-13-09Z"
ARCHES = {"amd64": "linux/amd64", "arm64": "linux/arm64"}


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def copy_required(source: Path, destination: Path) -> None:
    if not source.is_file():
        raise FileNotFoundError(source)
    destination.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(source, destination)
    os.chmod(destination, source.stat().st_mode & 0o777)


def write_env(path: Path, values: dict[str, str]) -> None:
    lines = ["# Generated by scripts/build_offline_bundle.py; do not edit."]
    for key, value in values.items():
        if any(char in value for char in "\n\r'"):
            raise ValueError(f"unsupported bundle env value for {key}")
        lines.append(f"{key}='{value}'")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def normalized_tarinfo(path: Path, arcname: str) -> tarfile.TarInfo:
    info = tarfile.TarInfo(arcname)
    stat = path.stat()
    info.size = stat.st_size
    info.mode = stat.st_mode & 0o777
    info.mtime = 0
    info.uid = 0
    info.gid = 0
    info.uname = ""
    info.gname = ""
    return info


def create_reproducible_tar_gz(source_dir: Path, output: Path) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("wb") as raw:
        with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0, compresslevel=9) as zipped:
            with tarfile.open(fileobj=zipped, mode="w", format=tarfile.PAX_FORMAT) as archive:
                for path in sorted(source_dir.rglob("*")):
                    relative = path.relative_to(source_dir)
                    arcname = f"{source_dir.name}/{relative.as_posix()}"
                    if path.is_dir():
                        info = normalized_tarinfo(path, arcname)
                        info.type = tarfile.DIRTYPE
                        info.size = 0
                        archive.addfile(info)
                    elif path.is_file():
                        info = normalized_tarinfo(path, arcname)
                        with path.open("rb") as handle:
                            archive.addfile(info, handle)


def build_bundle(
    *,
    root: Path,
    input_dir: Path,
    output_dir: Path,
    version: str,
    arch: str,
    image_prefix: str,
) -> tuple[Path, Path]:
    if arch not in ARCHES:
        raise ValueError(f"unsupported architecture: {arch}")
    bundle_name = f"dataflow-offline-{version}-{arch}"
    output = output_dir / f"{bundle_name}.tar.gz"
    checksum_output = output_dir / f"{bundle_name}.sha256"

    required = {
        "charts/dataflow.tgz": input_dir / "charts" / f"dataflow-{version}.tgz",
        "charts/kuberay-operator.tgz": input_dir
        / "charts"
        / f"kuberay-operator-{KUBERAY_VERSION}.tgz",
        "images/dataflow-runtime.tar": input_dir / "images" / "dataflow-runtime.tar",
        "images/dataflow-control-plane.tar": input_dir
        / "images"
        / "dataflow-control-plane.tar",
        "images/kuberay-operator.tar": input_dir / "images" / "kuberay-operator.tar",
        "images/postgres.tar": input_dir / "images" / "postgres.tar",
        "images/minio.tar": input_dir / "images" / "minio.tar",
    }
    scripts = {
        "scripts/load-images.sh": root / "release/offline/load-images.sh",
        "scripts/kind-load-images.sh": root / "release/offline/kind-load-images.sh",
        "scripts/install.sh": root / "release/offline/install.sh",
        "scripts/bootstrap-reference-deps.sh": root
        / "release/offline/bootstrap-reference-deps.sh",
    }

    with tempfile.TemporaryDirectory(prefix="dataflow-offline-") as temp:
        bundle = Path(temp) / bundle_name
        bundle.mkdir()
        for relative, source in required.items():
            copy_required(source, bundle / relative)
        for relative, source in scripts.items():
            destination = bundle / relative
            copy_required(source, destination)
            os.chmod(destination, 0o755)

        runtime_source = f"{image_prefix.rstrip('/')}/dataflow-runtime:{version}"
        control_source = f"{image_prefix.rstrip('/')}/dataflow-control-plane:{version}"
        env = {
            "DATAFLOW_VERSION": version,
            "DATAFLOW_ARCH": arch,
            "DATAFLOW_PLATFORM": ARCHES[arch],
            "KUBERAY_VERSION": KUBERAY_VERSION,
            "DATAFLOW_RUNTIME_SOURCE": runtime_source,
            "DATAFLOW_CONTROL_PLANE_SOURCE": control_source,
            "KUBERAY_OPERATOR_SOURCE": KUBERAY_OPERATOR_IMAGE,
            "POSTGRES_SOURCE": POSTGRES_IMAGE,
            "MINIO_SOURCE": MINIO_IMAGE,
        }
        write_env(bundle / "bundle.env", env)

        manifest = {
            "schema_version": 1,
            "dataflow_version": version,
            "architecture": arch,
            "platform": ARCHES[arch],
            "kuberay_version": KUBERAY_VERSION,
            "images": [
                {"archive": "images/dataflow-runtime.tar", "source": runtime_source},
                {"archive": "images/dataflow-control-plane.tar", "source": control_source},
                {"archive": "images/kuberay-operator.tar", "source": KUBERAY_OPERATOR_IMAGE},
                {
                    "archive": "images/postgres.tar",
                    "source": POSTGRES_IMAGE,
                    "purpose": "reference-bootstrap",
                },
                {
                    "archive": "images/minio.tar",
                    "source": MINIO_IMAGE,
                    "purpose": "reference-bootstrap",
                },
            ],
            "charts": [
                {"archive": "charts/dataflow.tgz", "name": "dataflow", "version": version},
                {
                    "archive": "charts/kuberay-operator.tgz",
                    "name": "kuberay-operator",
                    "version": KUBERAY_VERSION,
                },
            ],
        }
        (bundle / "manifest.json").write_text(
            json.dumps(manifest, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        (bundle / "README.md").write_text(
            f"""# DataFlow {version} offline bundle ({arch})

This bundle is self-contained for DataFlow/KubeRay installation in an air-gapped
Kubernetes environment. It includes architecture-specific application images,
the pinned KubeRay operator image/chart, local Helm charts, reference PostgreSQL
and MinIO images for non-production bootstrap testing, and install/load scripts.

Production deployments may ignore the reference PostgreSQL/MinIO images and
point DataFlow at existing in-network PostgreSQL and S3-compatible services.

Typical internal-registry flow:

```bash
./scripts/load-images.sh --registry registry.internal.example/dataflow
./scripts/install.sh \\
  --registry registry.internal.example/dataflow \\
  --namespace dataflow \\
  --database-secret dataflow-database \\
  --s3-secret dataflow-s3 \\
  --s3-endpoint http://minio.storage.svc.cluster.local:9000
```

Verify all payloads before use:

```bash
sha256sum -c SHA256SUMS
```
""",
            encoding="utf-8",
        )

        payloads = [
            path
            for path in bundle.rglob("*")
            if path.is_file() and path.name != "SHA256SUMS"
        ]
        checksum_lines = [
            f"{sha256(path)}  {path.relative_to(bundle).as_posix()}"
            for path in sorted(payloads, key=lambda item: item.relative_to(bundle).as_posix())
        ]
        (bundle / "SHA256SUMS").write_text(
            "\n".join(checksum_lines) + "\n",
            encoding="utf-8",
        )

        create_reproducible_tar_gz(bundle, output)

    checksum_output.write_text(
        f"{sha256(output)}  {output.name}\n",
        encoding="utf-8",
    )
    return output, checksum_output


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--input-dir", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--version", required=True)
    parser.add_argument("--arch", choices=sorted(ARCHES), required=True)
    parser.add_argument("--image-prefix", default="ghcr.io/tan90degrees")
    args = parser.parse_args()

    output, checksum = build_bundle(
        root=args.root.resolve(),
        input_dir=args.input_dir.resolve(),
        output_dir=args.output_dir.resolve(),
        version=args.version,
        arch=args.arch,
        image_prefix=args.image_prefix,
    )
    print(output)
    print(checksum)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
